### ISSUE TITLE
Extend the Autohop zone on surf_fruits S5/Strawberry

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#11]
**Describe the bug**
Right now the zone does not cover the leading edge of the surf platform. I feel like this is somewhat intentional based on the existing leading edge of the ahop zone, but I don't agree with partially covering this platform.

**To Reproduce**
1. Go to S5 on surf_fruits
2. Clear the first ramp and attempt to autohop on the leading edge of the platform with the ahop zone
3. Be surprised when your autohop doesn't go through

**Screenshots**
https://i.imgur.com/76Qlinz.png

**Comment by TeddiO** [comment]
I think the logic at the time was that if you end up flying straight in to the air (due to how the strawberry ramp works) and you clip the edge, you're not going to be able to clear that section anyways therefore it was better to encourage players to land deeper in to the platform to encourage momentum. 

Are you finding that you're barely clipping it and you're trying to save the run - or you're landing with momentum but you're just outside the range of the zone somehow?

**Comment by dwarfmagic** [comment]
More of a 'trying to save the run' rather than actually needing the zone extended to hit a route.
Seems weird that there is a cutoff there because it limits the player from having the attempt to continue the run.
Even if you couldn't continue it, doesn't make sense to stop the zone early if a hop is needed somewhere on the platform

**Comment by TeddiO** [comment]
I suppose it makes sense, a player has room to hop their way up in terms of speed to re-launch themselves which while isn't exactly ideal, this edge case doesn't particularly prevent either. For the interim I'll extend this to the full length of the platform (or at least, the bit that's missing) and when the new ahop system is available (which restricts how often you can hop in certain areas), this platform may be a candidate for that.

**Comment by TeddiO** [comment]
Fixed with next update
