### ISSUE TITLE
Bonus on surf_frost Does not Respawn the Player When Landing on the Ground

### ISSUE THREAD

**Issue by ChacoEleven** [BB-Games/gamemode-issues-requests#15]
**Describe the bug**
While playing on surf_frost, bonus1 does not have proper respawn areas for when players hit the ground forcing them to retype !bonus 1 to reset and try the bonus stage again. (I have no idea what the technical term is for player respawns when they hit the ground haha)

**Corresponding lauerror**
N/A

**To Reproduce**
1. Connect to the easy-surf server
2. /rtv or vote change the map to surf_frost
3. Complete the map
4. Type !bonus 1 in chat
5. Start walking forward until you're boosted off the spawn platform
6. Land anywhere you're not supposed to
7. Observe how you're not taken back to the bonus stage spawn and will have to type !bonus 1 in order to reset.

**~~Screenshots~~ Media**
https://i.imgur.com/hu4eDSU.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Binary Version: 64-bit

**Additional context**
I have no idea if this is even worth fixing as bonuses are not in the interest of [BB] however, this is a tad bit annoying when having to type !bonus 1 to reset the bonus stage.

During the discovery of this bug, I could literally walk anywhere and I would not respawn at any point.

**Comment by TeddiO** [comment]
This is a tricky one due to how the mapper set the map up with teleport destinations, I think they inadvertently don't work due to the cleanup process to ensure players players get spawned at the main route correctly. I'll revisit this and see if we can somehow get them working because while we don't give bonuses any extra attention; they should at least work.
