### ISSUE TITLE
Add option for tab-muting chat, not just voice chat

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#17]
**Is your feature request related to a problem? Please describe.**
I don't have the ability to sandbox or ballpit people, but I do have the ability to mute their voice chat in my menu.
However, especially in the case when someone is ballpitted, they usually resort to toxicity in text chat.
Normally this isn't a huge problem, but some people are super toxic.

**Why you would like to see this resolved, what does it enhance / bring to the table?**
When an admin isn't around to sandbox (which is a rare punishment compared to ballpitting anyhow) it can be frustrating to constantly see negativity in chat.

**Additional context**
A button next to the existing voice mute button on the scoreboard for a local chat mute would be nice.

**Comment by TeddiO** [comment]
So we actually have a way of doing this already, however we don't tend to advertise it. I guess the question is in such an event are you looking to make this permanent, or temporary?

This mostly boils down to the fact that there's no way to carry over "temporary" mutes easily between sessions whereas it's super easy to do it permanently (and again, we have this feature already).

**Comment by dwarfmagic** [comment]
I was unawares of any ways to mute someone's chat.
I would prefer having the existing option implemented in a more blatant
way, similar to the existing permanent voice mute.

**Comment by TeddiO** [comment]
The only reason it's not more blatant is mostly down to the fact that if a player feels the need to start outright ignoring other players, there's a debate there if admins etc should be stepping in. It was a tool designed intended to curb abuse more than "I don't want to hear this person for a bit".

However in console you can do `bb_ignoreplayer <steamid>` and that will prevent you from seeing any chat messages *and* hearing any of their voice either. This effect is permanent until you use `bb_unignoreplayer <steamid>`.  Does this fulfil your intended use case?

**Comment by dwarfmagic** [comment]
It seems like it's more complicated a step than it needs to be.
The primary case I see for using a feature like this is twofold:
1. An admin is not on to resolve the potential issue.
2. An admin is on, and hasn't decided to punish the player in question, but you personally don't want to interact with them.

In both cases, I don't see why it needs to be as complicated as running status to get someone's steam ID, and running another console command to mute their chat, when it's as easy as clicking an icon on the scoreboard to mute their voice.

At the least, I'd like to see an easier method of using the existing tool, rather than just assuming a staff member will always be online to fix the issue.

**Comment by TeddiO** [comment]
Working backwards for a moment here, 

The reason it accepts a SteamID and doesn't directly take a player object (currently) is the idea that if you wanted to ignore someone but they weren't currently online - you can still do so. That's not to say we couldn't make it more accessible (and parse it for you), but it leads on to my second point.

Generally if people are squabbling or have issues it only seems to get worse when both parties are willing to participate in the degradation and generally what we don't want to do is actively promote what could essentially lead to a silo'd system of abuse. An example of this if a person knows they're ignored, they may (and we've seen this) actively encourage other players to message the target instead. This causes bit of a weird scenario where the messengers may not know the extent of the issue and are unknowingly complicit in abuse, whereby if this issue festers and bubbles up to a point of where we have visibility: we can institute global punishments accordingly. 

To clarify, I'm not shooting down this debate or saying a "hard no", what I'm trying to work out exactly is the extent of the problem and is there actually a proper issue here. 

This very much isn't a technical issue but more of a social one, we'd much rather people get along rather than literally ignore other viewpoints. I appreciate you're seeking the ability to effectively "blot out" players for a while (because spam) and maybe there's a compromise we can reach in this regard. The issue is probably worse at the moment with the trial Platinum system during the anniversary event as those that are non-plat are effectively subject to a flood filter, but if everyone is Platinum then the system is effectively neutered.

**Comment by dwarfmagic** [comment]
There's not so much of an issue with spam or anything like that.
It's more to your argument that people are squabbling and being directly toxic/harassing a specific player.

For example, I was on the server recently and one player was being harassed by 3-4 other players, and clearly not having an enjoyable time.
Because of the lack of visibility, they don't have an easy way of completely blocking out the people who are harassing them.
Sure I can guide them to run this console command, but it's not something everyone is comfortable with, at least comparing to clicking a button on a GUI.

Another example was yesterday, I was interacting with someone who was extremely negative, who started off by engaging by asking for help. They devolved into a very negative attitude, but only ever used text chat. At this point I definitely would've muted them, because while they're not specifically harassing or bullying anyone, it's a negative interaction that I should ignore.
Having the ability to block out their chat is a good way to stop an interaction from escalating to the point where the enjoyment of the game is impacted.

I think making sure players receive proper punishment is a good intention, but staff aren't on all the time, and there needs to be some kind of compromise for allowing players to take matters into their own hands.
Like you said, there is a console command, but that's not something a new player would be able to tell easily.
Potentially an in-game report system could tie into implementing an ignore on someone? Like a /report <username> which would capture a chat log for admins to review later, and at the least provide some kind of follow-up route for staff later on?

**Comment by TeddiO** [comment]
So, I'm leaning towards your viewpoint and I can see where you're coming from, but what I suppose what I want to know (now) is why you didn't do /admin to call an admin for this (or did you?) because these would be players that we would seek to sandpit for generally being toxic.

**Comment by dwarfmagic** [comment]
Do you have a document of all the chat commands?
I'm sure I've heard of this being a command but I wouldn't have been able to say what it is for sure.

I don't think the problem is not having enough functionality, I think it's making the options somehow more accessible to players - especially new players.

**Comment by TeddiO** [comment]
If you do /admin <message> (fairly sure this is repeated in the ticker that spews out messages in yellow) it sends a request to all admins in our Slack & Discord (plus those on the server). There's an open ticket to have a command-generating function but it's still pending to be completed (mostly because commands don't have any descriptors given to them). 

I think that's fair in terms of making it at least more accessible and easier to notice. What I'm currently proposing then is:

- A mechanism is introduced to easily see ignored users via a UI (of which these users can also be removed from)
- Another mechanism that allows somehow a user to ignore a player (chat + voice), likely with a confirmation and an understanding of what they're doing through the interface. I'm not sure if this would make it on to the scoreboard because I still see this as a fairly destructive action (plus being able to ignore players like that is questionable). 
  - This feature effectively implements what's already exists on the client, just as a bridge effectively
- A message in the ticker that explains usage of the ignore feature somehow and how to access it.

**Comment by TeddiO** [comment]
Just a minor update, we're having internal discussions as to what's possible and what we want to achieve from this.

**Comment by TeddiO** [comment]
So internally we've come up with the following, which remixes some of the above:

- The UI will still be present but will include the ability to ignore for an hour (text), voice ignore (ala scoreboard) and outright ignore the player permanently (with appropriate confirmations). 
  - Voice will be the only one to remain on the scoreboard
- The chatbox will receive an enhancement where you can right click a message and ignore a players text chat for an hour (as well as some other outstanding things we've been meaning to add).
- The ticker message may be present, but likely will offer messages regarding right clicking a message instead of outright promoting the ignore system.

**Comment by TeddiO** [comment]
I appreciate it's been a while since any update on this - it's still at the forefront and is probably going to go live in the next few months. There's going to be some updates to `/admin` that while don't offer any straight up social controls, should hopefully offer some advice and make obvious steps players can take in the event of troublesome events.

**Comment by TeddiO** [comment]
So it's likely an update will go live later today that should satisfy this issue. There's been a few minor changes

- Players are able to remove ignored players fairly easily so there's no confirmation modal for this. Also seemed a bit moot given these have to be fairly specific actions
- The temporary chat mute will last for 45 minutes and cannot be directly removed. 
- The chatbox enhancement hasn't been added as that requires additional work to the chatbox yet to be done.
- `/admin` has received updates advising players of the new controls.
- Similar to `/admin`, the ticker has received a few updates in terms of messages about it. 
- If a player is blocked on your Steam friends list, they'll be passively ignored in-game as well now (this is shown on the `All Players` scroll)
- The menu can be brought up with the following chat commands: 
  - social
  - ignore
  - ignored
  - friends
  - mute
  - block
- To try and put a positive spin on this, it also allows you to easily see which of your Steam friends are connected.

**Comment by TeddiO** [comment]
For the sake of clarity and having this down somewhere, the line `If a player is blocked on your Steam friends list, they'll be passively ignored in-game as well now (this is shown on the All Players scroll)` is no longer correct due to an issue within GMod. If it gets resolved then this will automatically activate.
