### ISSUE TITLE
surf_guitar_hi shows on 'Surf - Easy' achievements

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#21]
Looking at the Map Completion section of the Easy server achievements still shows surf_guitar_hi
Additionally, the map completion count appears to be off of what is actually shown in my achievement list

https://i.imgur.com/wxOHB36.png

**Comment by TeddiO** [comment]
surf_guitar_hi will appear as you earned it previously. Those that didn't won't see it.

The completion count being off is due to the fact that we don't correctly subtract deprecated achievements (of ones you haven't earned) from the total count. It's been internally reported and should get fixed in the not too distant future.
