### ISSUE TITLE
Scoreboard showing incorrect stage

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#31]
**Describe the bug**
Seems like the scoreboard will show the wrong stage for freshly joined players.
Potentially based on what level someone was on when they left, and a new player taking their slot showing their old level.

**To Reproduce**
Have a few people in the lobby, on non stage-1
Have someone leave, and a new person join in their place
New person will show old stage number until they clear a stage.

**Screenshots**
https://i.imgur.com/nP1N90s.png

**Desktop (please complete the following information):**
Windows 64 bit (64 bit beta Gmod)

**Additional context**
Doesn't really break the game or anything, just noticed when checking ranks

**Comment by killermon** [comment]
That's interesting, technically, any player could pick up stale data from any other player.  Typically, if there's no data then it returns the first stage, but if there's stale data, then it returns that

**Comment by TeddiO** [comment]
I assume that's because we're storing individual players with UserID() so if someone takes their place fast enough and the panel isn't cleaned up by that point, it'll reuse the panel but keep the old data. 

I suppose the question is are we potentially leaking any memory we shouldn't be in this scenario?

**Comment by TeddiO** [comment]
As of the next update this should be resolved.
