### ISSUE TITLE
Steam Performance Issues

### ISSUE THREAD

**Issue by bbkaiden** [BB-Games/gamemode-issues-requests#54]
The server can become laggy and unplayable during times of Steam disruption, downtime, or maintenance. This shouldn't be the case and it disrupts times, runs etc. Can it be identified and patched so the server isn't disrupted by Steam maintenance or availability, Steam shouldn't impact server performance, it's probably a matter of time before a longer period of downtime is encountered.

**Comment by bbkaiden** [comment]
Could be worth unlinking steam from at least Easy while this is investigated, seems to be having quite a large impact on Tuesdays, and sometimes Steam maint can be extended.

**Comment by TeddiO** [comment]
Some updates have been made to see if it improves the situation at all. Will continue to monitor.

**Comment by TeddiO** [comment]
Changes didn't seem to yield the improvements we were after, extra debugging / logging has been added.

**Comment by TeddiO** [comment]
So after doing research, testing and further tracking this issue is an issue caused by Valve / Steam and not something we've done. Testing without our steam-related binary modules has shown that this issue persists and the issue is made worse by the amount of players on the server at this point in time.

The majority of the time maintenance is < 10 minutes and is on a specific day so we can add in warnings and alert players - but that's about it.
