### ISSUE TITLE
[Surf] Map vote overhaul

### ISSUE THREAD

**Issue by Swingbiter** [BB-Games/gamemode-issues-requests#56]
Issue: A lot of the same maps are played over and over. I hate to join just to find out we're on Kitsune or Nyx again. I find that maps being listed lower that you have to scroll to prevent them from winning votes as well.

This can be resolved in a few ways.

- A cube modifier based on how long it has been since that map has been played. (1.25x, 1.5x, ...)

- A smaller selection of maps to choose from each vote. This would allow for lesser seen maps to be voted for.

A combination of these two would boost rarely seen maps play rate immensely.

**Comment by TeddiO** [comment]
The problem we see with this style of complaint is we have a fairly aggressive cooldown weighting system on maps and both the maps you've mentioned are on 12 hour cooldowns meaning that any given map can only be played for a maximum of 1 hour a day (ignoring extends for a moment). What also doesn't help is those are some of our most popular maps (going by played minutes from unique players) so realistically it's bit of a conundrum. 

If a map can only take up 1/24th of a day _and_ it's favoured strongly by players it already means that we're already very much applying a compromise here given players seem to want to play these maps heavily! I agree the votemap system could be improved and significantly so - but I don't think the issue lies with the maps themselves but more around the mechanisms of how maps are added to the list, things such as blind voting, random map times and so on.

**Comment by bbkaiden** [comment]
Have suggested the cube bonuses to less popular maps in the past, I think it'd be good and see them get voted more potentially.

I'm not sure what determines what appears at the top of the vote list but it seems somewhat fixed, could be better if it was completely random every time.

Agree on map cooldowns - 12h cooldowns are already in place for frequently voted maps which I think is fine.

**Comment by Niflheimrx** [comment]
Personally I don't think giving a cube bonus modifier to maps that haven't been playing for a while isn't going to change anything. I think the issue lies in the mappool itself as newer players are going to pick a map that sounds most familiar. Like Teddi said the maps you mentioned just happen to be the most popular maps on surf so when those options become available people will pick them regardless.

I myself am very lazy when picking maps so when the mapvote comes up I will pick whatever is most familiar to me at the top of the list, so an idea that I had was that there should be some type of sorting that will prioritize maps that haven't been played for a while at the top of the list while the most recently played maps stay at the bottom, so players will have to go through the process of scrolling down to find the map they are looking for. I'm not sure if that's already in place but I have seen kitsune at the top of the list before. It might not be the best solution but I think it's better than having beginner and kitsune at the top of the list as it gives something like apollo a chance to be seen by newer players.

**Comment by bbkaiden** [comment]
Random Map option above the rest would be nice, could assign all votes for it at the end to a single map chosen at random.

![image](https://user-images.githubusercontent.com/4204891/208759090-330b1b9e-ad23-4030-9d84-69e94e054e1e.png)

**Comment by TeddiO** [comment]
Closing this as https://github.com/BB-Games/gamemode-issues-requests/issues/63 has the request from https://github.com/BB-Games/gamemode-issues-requests/issues/56#issuecomment-1360131047
