### ISSUE TITLE
Bidding on own Items

### ISSUE THREAD

**Issue by bbkaiden** [BB-Games/gamemode-issues-requests#66]
At present you can bid on your own items/outbid yourself.

I feel if you're the current bidder you shouldn't be able to bid again, effectively against yourself. Can see some have done this to farm achievements.

On eBay you can't bid against yourself, only set up automatic bids which bids again if someone else does, or increase your current maximum bid. I can't imagine a system like that on the market at present, so best to just block further bids if they're current the winner I feel.

**Comment by TeddiO** [comment]
I believe this only applies to the bazaar and not the general marketplace, as the marketplace shows something like:
![31401eaa-39b8-4f68-b84a-ede617c29e36n-DimgraySpiketail](https://github.com/BB-Games/gamemode-issues-requests/assets/1713740/a342266b-56ac-48b3-9e26-1aa2f6fb0ede)

At this point (in the bazaar) a player can only bid higher than themselves - is that undesirable behaviour? They'd need surplus Cubes to push the price higher

**Comment by killermon** [comment]
Blocking people bidding against themselves (At least clientside), is quite simple and doing it clientside would be enough I think. Serverside and in the DB a bit trickier. However, it was a very deliberate choice allowing people to do it, as if you bid on an item, and then later go "maybe I should have bid more" before say, leaving for the evening, it's nice to outbid yourself. Especially if you know you will be outbid by someone when you won't be around to rebid.

The core of the issue is that any cubes received - from anywhere - including those form the market refunds, trigger the cubes earned stat tracker. And bidding on items likewise triggers the bbase_cubes_spent stat tracker.

The former isn't too hard to fix ( would just need a new delivery type, and exposing a bool on the DepositCubes function ). The latter, bbase_cubes_spent, if we wanted it to be accurate (E.g. you WIN a bid and we still count cubes spent), then it's just doing to be a complete nightmare.

**Comment by TeddiO** [comment]
I've made it so when items are returned from the marketplace, they no longer contribute to the "Cubes earned" stat. As for expenditures, 🤷 without building an extra bit to support that, it won't be possible under our current tech
