### ISSUE TITLE
Invisible ramps and parts of the map on the replay on surf_indecisive

### ISSUE THREAD

**Issue by KamilRa** [BB-Games/gamemode-issues-requests#72]
**Describe the bug**
If you watch a reply on surf_indecisive, quite a few ramps are missing, as well as some textures on the "cosmic" part of the map. Tried on time by Senohh.

**Corresponding lua error**
Doesn't seem to show anything around the time this is happening

**How to reproduce the issue**
1. Be on surf_indecisive
2.  Go into F1
3. Go into timetrails
4. Find Senohh's time
5. Watch it
6. See the issue right after the sandy part is done

**Screenshots**
https://files.catbox.moe/ulbgeq.png

**System Information:**
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 18:05:22 Jul 22 2024 (9379) (4000)
GMod version 2024.08.09, branch: x86-64, multicore: 1
Windows 64bit
 ```

**Additional context**
Off topic, but while I was trying to sing in to the forum, the privacy policy link doesn't seem to work

**Comment by TeddiO** [comment]
Thanks for the report!

The issue is known, and it's essentially to do with PVS. The runs themselves aren't broken, however the engine simply isn't loading in that part of the world as it doesn't believe that you're there. It likely won't be resolved until the end of the week but something is in the works to resolve it.

**Comment by TeddiO** [comment]
When this issue is closed, within about an hour changes should be live that help improve / correct this issue.
