### ISSUE TITLE
Seasonal hiscore viewer (maybe alltimes too?)

### ISSUE THREAD

**Issue by dwarfmagic** [BB-Games/gamemode-issues-requests#9]
**Is your feature request related to a problem? Please describe.**
I am literally incapable of seeing the times for a map the server is not on. If I haven't been on for every map rotation the server goes to, someone can beat my time on a map and I have no idea which map they were able to beat.
In actuality anyone can beat my times because they're really mediocre, but I want to accept my lack of skill head-on.

**Why you would like to see this resolved, what does it enhance / bring to the table?**
By showing the seasonal hiscores, I would be able to see which maps I have yet to set a seasonal time on, as well as which times I need to improve. This gives me better context on what map to vote for.

**Additional context**
It doesn't necessarily have to be out of the gmod client that we can see times, just somewhere that we can see what place on what map. Could definitely get a format example if desired.
Give me the times viewer ree

**Comment by TeddiO** [comment]
This is something we're admittedly lacking at the moment, though I think the issue you're describing is actually two separate issues. 

We do currently expose weekly/monthly/all-time via our web API but we've yet to actually build a web-frontend for it. We did have a proof-of-concept frontend for it by Ender a while back but at the time it was bottom of the list (and the front-end is now dead). I might stitch together something so that information can at least be viewed along with seasonal records - but this may come after the API redesign, very much a "watch this space".

The second issue you mention about checking who has beat you on a record is actually a bit troublesome currently as we only calculate seasonal records once per day. This is looking to be something we make an hourly process but it requires being unchained from the core gamemode itself. 

Ultimately I'm going to treat this particular request as a "I want frontend so I can see my records", as the second point is more inferred than it is requested.

**Comment by killermon** [comment]
We could expose the weekly / monthly / all-time records via the surf telemetry screen?

**Comment by TeddiO** [comment]
I think if we were to offer it in-game, it'd be best via an HTML panel or still via the web API (with a json object), the less srcds fundamentally has to do, the better.

**Comment by killermon** [comment]
Happy for the web API - my only concern about the HTML panel is how poor the currently Gmod HTML panel and it's inability to do anything remotely modern.

**Comment by killermon** [comment]
I also don't have access to where-ever the Web API is hosted nor the code it runs on plz

**Comment by TeddiO** [comment]
Turns out I added seasonal support for the latest season in the web-api, I've linked you the documentation for the web API as well.

**Comment by TeddiO** [comment]
Just an update that this is paused until the new API is written, but I'm happy to announce that's in progress 😄

**Comment by TeddiO** [comment]
API v2 is out and the announcement has been issued across relevant channels. While this request is still very much valid (and a goal) it's now possible for those of a more developer inclination to build their own tools for this.

**Comment by TeddiO** [comment]
This feature will be live in-game in the next 30 minutes or so.
